### ISSUE TITLE
Yarn compilation error on production profile

### ISSUE THREAD

**Issue by anwar-elmawardy** [k3nsei/ng-in-viewport#42]
`yarn run webpack:prod`
 ERROR in node_modules/ng-in-viewport/in-viewport/in-viewport.directive.d.ts(3,49): error TS1005: '=' expected.

**Comment by k3nsei** [comment]
@anwar-elmawardy I can not help you. You have not provided enough information.

**Comment by OzoTek** [comment]
Hi @k3nsei,

I ran into the same issue, here's the line causing the error:
`export declare const InViewportMetadata: unique symbol;`

The error comes from TypeScript compilation.

Angular : `5.2.9`
ng-in-viewport: `^1.2.7-hotfix.1 `
intersection-observer: `^0.5.0`

Let me know if you need further informations.

**Comment by k3nsei** [comment]
@anwar-elmawardy @OzoTek Can you try with typescript >= 2.8 ??

**Comment by OzoTek** [comment]
It compiles indeed, but I get warnings from Angular 5 because it supports only TS < 2.7.
So your lib needs Angular >= 6 to be used safely apparently.

If you could either update the peer dependencies (or support TS < 2.8) that would be nice, to avoid future confusions :)

Thanks.

**Comment by k3nsei** [comment]
v1.2.8 is build with typescript 2.6.2. So it should be works right now.

**Comment by k3nsei** [comment]
@all-contributors please add @anwar-elmawardy for bug
@all-contributors please add @OzoTek for bug

**Comment by k3nsei** [comment]
@all-contributors please add @anwar-elmawardy for bug

**Comment by k3nsei** [comment]
@all-contributors please add @OzoTek  for bug

**Comment by nickmaglowsch** [comment]
Hello, was just trying out the lib on angular 5.2.10 and had the same issue using intersection-observer 0.12.0 and ng-in-viewport 6.1.5. should i use a specific version to be compatible with angular 5 or something? thanks in advance
